### PR TITLE
New interface for segment load/store and remove tuple types.

### PR DESCRIPTION
**Pull request by kito-cheng**
This PR is for https://github.com/riscv/rvv-intrinsic-doc/issues/95.

- New interface for segment load/store
- Remove all tuple type related API

### CODE REVIEW

**Review by nick-knight — CHANGES_REQUESTED** [review]
Perhaps I'm misunderstanding this commit, but there appear to be some changes unrelated to Zvlsseg and tuple types. For example, the semantic vector functions are deleted. I suggest splitting this into multiple PRs.

**Comment by kito-cheng** [comment]
Thanks, added back :)

**Comment by Hsiangkai** [comment]
LGTM.

**Comment by topperc** [comment]
Are we ready to push this?

**Comment by Hsiangkai** [comment]
There are conflicting files. @kito-cheng may need to update the PR based on the latest version.

**Comment by zakk0610** [comment]
> Are we ready to push this?

Yes, #95 have more people agree this changed, so LGTM.

**Review by Hsiangkai — APPROVED** [review]
Let's get it in to have a workable solution first. If there is better solution later, we could refine it.

We have different intrinsic name, `vlseg2e8_v_i8m1`, from the tuple one, `vlseg2e8_v_i8m1x2`. If we want to recover tuple types later, there is no conflict here.

**Comment by kito-cheng** [comment]
Rebased.

**Comment by Hsiangkai** [comment]
Why are semantic vector functions deleted?

**Comment by kito-cheng** [comment]
Add back semantic vector functions.

**Comment by Hsiangkai** [comment]
LGTM.

**Pull request merged**
