### PR TITLE
Add Copyright and License Information

### PR DESCRIPTION
**Pull request by kito-cheng**
Hi guys:

We don't have copyright and license information and I think we should have one, so I add `CC-BY-4.0` for doc and `BSD-3-Clause ` for code, but I believe it require all author/contributor OK for this.

So please leave a simple `OK` or something equivalence word here if it's OK to you on list on the copyright list and OK to changing license to `CC-BY-4.0` and `BSD-3-Clause`, in case you are not OK with this, feel free to leave message here or drop a mail to me.

@zakk0610 @Hsiangkai @xingmingjie @rofirrim @HanKuanChen @knightsifive @issuehsu

### CODE REVIEW

**Comment by xingmingjie** [comment]
LGTM，OK

**Review by issuehsu — APPROVED** [review]
OK for me

**Comment by zakk0610** [comment]
LGTM.

**Comment by rofirrim** [comment]
LGTM

**Comment by HanKuanChen** [comment]
LGTM

**Comment by Hsiangkai** [comment]
LGTM.

**Comment by knightsifive** [comment]
LGTM!

**Comment by kito-cheng** [comment]
Thanks everyone, I think we already gather the response from all author :)

**Pull request merged**
